services:
  - type: web
    name: re-moda-backend
    env: node
    plan: starter
    buildCommand: npm install && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-2
      - key: AWS_S3_BUCKET_NAME
        value: clothing-items-remoda
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAID_API_KEY
        sync: false
      - key: REPLICATE_API_KEY
        sync: false 